theme = "slick"
icons = "awesome"

[[block]]
block = "music"
player = "clementine"
buttons = ["prev", "play", "next"]
max_width = 40

[[block]]
block = "disk_space"
path = "/home"
alias = "Home:"
info_type = "available"
unit = "GB"
interval = 60
warning = 25.0
alert = 10.0

[[block]]
block = "disk_space"
path = "/"
alias = "Root:"
info_type = "available"
unit = "GB"
interval = 60
warning = 18.0
alert = 10.0

[[block]]
block = "uptime"

[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "{max}° max"
chip = "*-isa-*"
good=46
warning = 68

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"

[[block]]
block = "cpu"
interval = 2

[[block]]
block = "weather"
format = "{weather} ({location}) {temp}°, {wind} m/s {direction}"
# Hyderabad
service = { name = "openweathermap", api_key = "xxx", city_id = "1269843", units = "metric" }
